// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getCredentials: (provider: CloudProviderName) => typedError<{
	provider: "AWS",
} & AwsCredentials | {
	provider: "ORACLE",
} & OracleCredentials | {
	provider: "GCP",
} & GcpCredentials | {
	provider: "AZURE",
} & AzureCredentials | null, string>(__TAURI_INVOKE("get_credentials", { provider })),
	saveCredentials: (credentials: ProviderCredentials) => typedError<null, string>(__TAURI_INVOKE("save_credentials", { credentials })),
	deleteCredentials: (provider: CloudProviderName) => typedError<null, string>(__TAURI_INVOKE("delete_credentials", { provider })),
	verifyPermissions: (provider: CloudProviderName) => typedError<PermissionStatus[], string>(__TAURI_INVOKE("verify_permissions", { provider })),
	spawnInstance: (region: string, provider: CloudProviderName, onEvent: Channel<SpawnInstanceEvent>) => typedError<null, string>(__TAURI_INVOKE("spawn_instance", { region, provider, onEvent })),
	terminateInstance: (instanceId: string, region: string, provider: CloudProviderName) => typedError<string, string>(__TAURI_INVOKE("terminate_instance", { instanceId, region, provider })),
	listInstances: (region: string | null) => typedError<InstanceInfo[], string>(__TAURI_INVOKE("list_instances", { region })),
	hasProfile: () => typedError<boolean, string>(__TAURI_INVOKE("has_profile")),
	provisionAccount: (provider: CloudProviderName, onEvent: Channel<ProvisionAccountEvent>) => typedError<null, string>(__TAURI_INVOKE("provision_account", { provider, onEvent })),
	enableRegion: (region: string, provider: CloudProviderName, onEvent: Channel<EnableRegionEvent>) => typedError<null, string>(__TAURI_INVOKE("enable_region", { region, provider, onEvent })),
	getRegions: (provider: CloudProviderName) => typedError<Region[], string>(__TAURI_INVOKE("get_regions", { provider })),
	connect: (instanceId: string, region: string, provider: CloudProviderName, publicIpV4: string | null, publicIpV6: string | null) => typedError<string, string>(__TAURI_INVOKE("connect", { instanceId, region, provider, publicIpV4, publicIpV6 })),
	disconnect: () => typedError<string, string>(__TAURI_INVOKE("disconnect")),
	getVpnStatus: () => typedError<VpnStatus_Serialize, string>(__TAURI_INVOKE("get_vpn_status")),
	subscribeToVpnStatus: () => typedError<null, string>(__TAURI_INVOKE("subscribe_to_vpn_status")),
	getInstancePricing: (provider: CloudProviderName, instanceType: string) => typedError<PricingInfo, string>(__TAURI_INVOKE("get_instance_pricing", { provider, instanceType })),
	getLedger: () => typedError<LedgerEntry[], string>(__TAURI_INVOKE("get_ledger")),
	saveFile: (path: string, content: string) => typedError<null, string>(__TAURI_INVOKE("save_file", { path, content })),
	listActiveSpawnJobs: () => typedError<SpawnJobState[], string>(__TAURI_INVOKE("list_active_spawn_jobs")),
	dismissSpawnJob: (jobId: string) => typedError<null, string>(__TAURI_INVOKE("dismiss_spawn_job", { jobId })),
	getNotificationSettings: () => __TAURI_INVOKE<NotificationSettings>("get_notification_settings"),
	saveNotificationSettings: (settings: NotificationSettings) => typedError<null, string>(__TAURI_INVOKE("save_notification_settings", { settings })),
	getAutoTerminateSettings: () => __TAURI_INVOKE<AutoTerminateSettings>("get_auto_terminate_settings"),
	saveAutoTerminateSettings: (settings: AutoTerminateSettings) => typedError<null, string>(__TAURI_INVOKE("save_auto_terminate_settings", { settings })),
	getVpnSettings: () => __TAURI_INVOKE<VpnSettings>("get_vpn_settings"),
	saveVpnSettings: (settings: VpnSettings) => typedError<null, string>(__TAURI_INVOKE("save_vpn_settings", { settings })),
};

/** Events */
export const events = {
	instanceAutoTerminated: makeEvent<InstanceAutoTerminatedEvent>("instance-auto-terminated"),
	vpnStatus: makeEvent<VpnStatusEvent_Deserialize>("vpn-status"),
};

/* Types */
export type AutoTerminateSettings = {
	autoTerminateEnabled: boolean,
	autoTerminateThresholdMinutes: number,
	autoTerminateUnit: DurationUnit,
};

export type AwsCredentials = {
	accessKeyId: string,
	secretAccessKey: string,
};

export type AzureCredentials = {
	subscriptionId: string,
	tenantId: string,
	applicationId: string,
	secretValue: string,
};

export type CloudProviderName = "AWS" | "AZURE" | "GCP" | "ORACLE";

export type ConnectedInstance = {
	instanceId: string,
	publicIpV4: string | null,
	publicIpV6: string | null,
	region: string,
	provider: CloudProviderName,
};

export type DurationUnit = "minutes" | "hours";

export type EnableRegionEvent = { kind: "STARTED"; jobId: string; steps: SpawnStep[] } | { kind: "PROGRESS"; stepId: string; status: SpawnStepStatus; error: string | null } | { kind: "COMPLETE"; region: string } | { kind: "FAILED"; error: string };

export type GcpCredentials = {
	projectId: string,
	serviceAccountJson: string,
};

export type InstanceAutoTerminatedEvent = {
	instanceId: string,
};

export type InstanceInfo = {
	id: string,
	name: string | null,
	region: string,
	state: InstanceState,
	errorReason: string | null,
	publicIpV4: string,
	publicIpV6: string,
	provider: CloudProviderName,
	instanceType: string,
	launchedAt: string | null,
	spawnId: string | null,
};

export type InstanceState = "SPAWNING" | "INSTALLING" | "ERROR" | "RUNNING" | "STOPPING" | "STOPPED" | "UNKNOWN";

export type LedgerEntry = {
	instanceId: string,
	provider: CloudProviderName,
	region: string,
	instanceType: string,
	launchedAt: string,
	terminatedAt: string | null,
	idleSince?: string | null,
	setupComplete?: boolean,
	bytesSent: number,
	bytesReceived: number,
};

export type NotificationSettings = {
	notificationEnabled: boolean,
	notificationThresholdMinutes: number,
	notificationUnit: DurationUnit,
};

export type OracleCredentials = {
	tenancyOcid: string,
	userOcid: string,
	fingerprint: string,
	privateKeyPem: string,
	region: string,
};

export type PermissionStatus = {
	permission: string,
	granted: boolean,
};

export type PricingInfo = {
	hourlyRate: number | null,
	ipHourlyRate: number | null,
	egressRatePerGb: number | null,
	storageGb: number | null,
	storageRatePerGbMonth: number | null,
};

export type ProviderCredentials = {
	provider: "AWS",
} & AwsCredentials | {
	provider: "ORACLE",
} & OracleCredentials | {
	provider: "GCP",
} & GcpCredentials | {
	provider: "AZURE",
} & AzureCredentials;

export type ProvisionAccountEvent = { kind: "STARTED"; jobId: string; steps: SpawnStep[] } | { kind: "PROGRESS"; stepId: string; status: SpawnStepStatus; error: string | null } | { kind: "COMPLETE"; provider: CloudProviderName } | { kind: "FAILED"; error: string };

export type Region = {
	name: string,
	country: string,
};

export type SpawnInstanceEvent = { kind: "STARTED"; job: SpawnJobState } | { kind: "PROGRESS"; stepId: string; status: SpawnStepStatus; error: string | null } | { kind: "INSTANCE_LAUNCHED"; instance: InstanceInfo } | { kind: "COMPLETE"; instance: InstanceInfo } | { kind: "FAILED"; error: string };

export type SpawnJobState = {
	jobId: string,
	region: string,
	provider: CloudProviderName,
	instanceId: string | null,
	status: SpawnJobStatus,
	error: string | null,
	steps: SpawnJobStep[],
};

export type SpawnJobStatus = "RUNNING" | "FAILED";

export type SpawnJobStep = {
	id: string,
	label: string,
	status: SpawnStepStatus,
	error: string | null,
};

export type SpawnStep = {
	id: string,
	label: string,
};

export type SpawnStepStatus = "PENDING" | "RUNNING" | "COMPLETED" | "FAILED";

export type TunnelMetrics = {
	bytesSent: number,
	bytesReceived: number,
	packetsSent: number,
	packetsReceived: number,
	uploadRate: number,
	downloadRate: number,
};

export type VpnSettings = {
	sessionKillswitch: boolean,
};

export type VpnStatus = VpnStatus_Serialize | VpnStatus_Deserialize;

export type VpnStatusEvent = VpnStatusEvent_Serialize | VpnStatusEvent_Deserialize;

export type VpnStatusEvent_Deserialize = VpnStatus_Deserialize;

export type VpnStatusEvent_Serialize = VpnStatus_Serialize;

export type VpnStatus_Deserialize = {
	connected: boolean,
	instance: ConnectedInstance | null,
	metrics: TunnelMetrics | null,
	connectedAt: number | null,
	connectionError?: string | null,
};

export type VpnStatus_Serialize = {
	connected: boolean,
	instance: ConnectedInstance | null,
	metrics: TunnelMetrics | null,
	connectedAt: number | null,
	connectionError?: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

