interface RegionInfo {
  city: string;
  countryCode: string;
}

const AWS_REGION_INFO: Record<string, RegionInfo> = {
  "us-east-1": { city: "N. Virginia", countryCode: "us" },
  "us-east-2": { city: "Ohio", countryCode: "us" },
  "us-west-1": { city: "N. California", countryCode: "us" },
  "us-west-2": { city: "Oregon", countryCode: "us" },
  "ca-central-1": { city: "Montréal", countryCode: "ca" },
  "ca-west-1": { city: "Calgary", countryCode: "ca" },
  "eu-west-1": { city: "Ireland", countryCode: "ie" },
  "eu-west-2": { city: "London", countryCode: "gb" },
  "eu-west-3": { city: "Paris", countryCode: "fr" },
  "eu-central-1": { city: "Frankfurt", countryCode: "de" },
  "eu-central-2": { city: "Zurich", countryCode: "ch" },
  "eu-north-1": { city: "Stockholm", countryCode: "se" },
  "eu-south-1": { city: "Milan", countryCode: "it" },
  "eu-south-2": { city: "Spain", countryCode: "es" },
  "ap-east-1": { city: "Hong Kong", countryCode: "hk" },
  "ap-northeast-1": { city: "Tokyo", countryCode: "jp" },
  "ap-northeast-2": { city: "Seoul", countryCode: "kr" },
  "ap-northeast-3": { city: "Osaka", countryCode: "jp" },
  "ap-southeast-1": { city: "Singapore", countryCode: "sg" },
  "ap-southeast-2": { city: "Sydney", countryCode: "au" },
  "ap-southeast-3": { city: "Jakarta", countryCode: "id" },
  "ap-southeast-4": { city: "Melbourne", countryCode: "au" },
  "ap-southeast-5": { city: "Kuala Lumpur", countryCode: "my" },
  "ap-southeast-7": { city: "Bangkok", countryCode: "th" },
  "ap-south-1": { city: "Mumbai", countryCode: "in" },
  "ap-south-2": { city: "Hyderabad", countryCode: "in" },
  "sa-east-1": { city: "São Paulo", countryCode: "br" },
  "me-south-1": { city: "Bahrain", countryCode: "bh" },
  "me-central-1": { city: "UAE", countryCode: "ae" },
  "af-south-1": { city: "Cape Town", countryCode: "za" },
  "il-central-1": { city: "Tel Aviv", countryCode: "il" },
  "mx-central-1": { city: "Mexico City", countryCode: "mx" },
};

const GCP_REGION_INFO: Record<string, RegionInfo> = {
  "us-central1": { city: "Iowa", countryCode: "us" },
  "us-east1": { city: "S. Carolina", countryCode: "us" },
  "us-east4": { city: "N. Virginia", countryCode: "us" },
  "us-east5": { city: "Columbus", countryCode: "us" },
  "us-south1": { city: "Dallas", countryCode: "us" },
  "us-west1": { city: "Oregon", countryCode: "us" },
  "us-west2": { city: "Los Angeles", countryCode: "us" },
  "us-west3": { city: "Salt Lake City", countryCode: "us" },
  "us-west4": { city: "Las Vegas", countryCode: "us" },
  "northamerica-northeast1": { city: "Montréal", countryCode: "ca" },
  "northamerica-northeast2": { city: "Toronto", countryCode: "ca" },
  "northamerica-south1": { city: "Querétaro", countryCode: "mx" },
  "southamerica-east1": { city: "São Paulo", countryCode: "br" },
  "southamerica-west1": { city: "Santiago", countryCode: "cl" },
  "europe-west1": { city: "Belgium", countryCode: "be" },
  "europe-west2": { city: "London", countryCode: "gb" },
  "europe-west3": { city: "Frankfurt", countryCode: "de" },
  "europe-west4": { city: "Netherlands", countryCode: "nl" },
  "europe-west6": { city: "Zurich", countryCode: "ch" },
  "europe-west8": { city: "Milan", countryCode: "it" },
  "europe-west9": { city: "Paris", countryCode: "fr" },
  "europe-west10": { city: "Berlin", countryCode: "de" },
  "europe-west12": { city: "Turin", countryCode: "it" },
  "europe-north1": { city: "Finland", countryCode: "fi" },
  "europe-central2": { city: "Warsaw", countryCode: "pl" },
  "europe-southwest1": { city: "Madrid", countryCode: "es" },
  "asia-east1": { city: "Taiwan", countryCode: "tw" },
  "asia-east2": { city: "Hong Kong", countryCode: "hk" },
  "asia-northeast1": { city: "Tokyo", countryCode: "jp" },
  "asia-northeast2": { city: "Osaka", countryCode: "jp" },
  "asia-northeast3": { city: "Seoul", countryCode: "kr" },
  "asia-south1": { city: "Mumbai", countryCode: "in" },
  "asia-south2": { city: "Delhi", countryCode: "in" },
  "asia-southeast1": { city: "Singapore", countryCode: "sg" },
  "asia-southeast2": { city: "Jakarta", countryCode: "id" },
  "australia-southeast1": { city: "Sydney", countryCode: "au" },
  "australia-southeast2": { city: "Melbourne", countryCode: "au" },
  "me-west1": { city: "Tel Aviv", countryCode: "il" },
  "me-central1": { city: "Doha", countryCode: "qa" },
  "me-central2": { city: "Dammam", countryCode: "sa" },
  "africa-south1": { city: "Johannesburg", countryCode: "za" },
  "europe-north2": { city: "Stockholm", countryCode: "se" },
  "asia-southeast3": { city: "Bangkok", countryCode: "th" },
};

const AZURE_REGION_INFO: Record<string, RegionInfo> = {
  "eastus": { city: "Virginia", countryCode: "us" },
  "eastus2": { city: "Virginia", countryCode: "us" },
  "westus": { city: "California", countryCode: "us" },
  "westus2": { city: "Washington", countryCode: "us" },
  "westus3": { city: "Arizona", countryCode: "us" },
  "centralus": { city: "Iowa", countryCode: "us" },
  "northcentralus": { city: "Illinois", countryCode: "us" },
  "southcentralus": { city: "Texas", countryCode: "us" },
  "westcentralus": { city: "Wyoming", countryCode: "us" },
  "canadacentral": { city: "Toronto", countryCode: "ca" },
  "canadaeast": { city: "Québec", countryCode: "ca" },
  "brazilsouth": { city: "São Paulo", countryCode: "br" },
  "brazilsoutheast": { city: "Rio de Janeiro", countryCode: "br" },
  "northeurope": { city: "Ireland", countryCode: "ie" },
  "westeurope": { city: "Netherlands", countryCode: "nl" },
  "uksouth": { city: "London", countryCode: "gb" },
  "ukwest": { city: "Cardiff", countryCode: "gb" },
  "francecentral": { city: "Paris", countryCode: "fr" },
  "francesouth": { city: "Marseille", countryCode: "fr" },
  "germanywestcentral": { city: "Frankfurt", countryCode: "de" },
  "germanynorth": { city: "Berlin", countryCode: "de" },
  "switzerlandnorth": { city: "Zurich", countryCode: "ch" },
  "switzerlandwest": { city: "Geneva", countryCode: "ch" },
  "norwayeast": { city: "Oslo", countryCode: "no" },
  "norwaywest": { city: "Norway", countryCode: "no" },
  "swedencentral": { city: "Gävle", countryCode: "se" },
  "polandcentral": { city: "Warsaw", countryCode: "pl" },
  "italynorth": { city: "Milan", countryCode: "it" },
  "spaincentral": { city: "Madrid", countryCode: "es" },
  "eastasia": { city: "Hong Kong", countryCode: "hk" },
  "southeastasia": { city: "Singapore", countryCode: "sg" },
  "japaneast": { city: "Tokyo", countryCode: "jp" },
  "japanwest": { city: "Osaka", countryCode: "jp" },
  "koreacentral": { city: "Seoul", countryCode: "kr" },
  "koreasouth": { city: "Busan", countryCode: "kr" },
  "australiaeast": { city: "Sydney", countryCode: "au" },
  "australiasoutheast": { city: "Melbourne", countryCode: "au" },
  "australiacentral": { city: "Canberra", countryCode: "au" },
  "australiacentral2": { city: "Canberra", countryCode: "au" },
  "centralindia": { city: "Pune", countryCode: "in" },
  "southindia": { city: "Chennai", countryCode: "in" },
  "westindia": { city: "Mumbai", countryCode: "in" },
  "jioindiawest": { city: "Jamnagar", countryCode: "in" },
  "jioindiacentral": { city: "Nagpur", countryCode: "in" },
  "uaenorth": { city: "Dubai", countryCode: "ae" },
  "uaecentral": { city: "Abu Dhabi", countryCode: "ae" },
  "southafricanorth": { city: "Johannesburg", countryCode: "za" },
  "southafricawest": { city: "Cape Town", countryCode: "za" },
  "israelcentral": { city: "Tel Aviv", countryCode: "il" },
  "qatarcentral": { city: "Doha", countryCode: "qa" },
  "mexicocentral": { city: "Querétaro", countryCode: "mx" },
  "newzealandnorth": { city: "Auckland", countryCode: "nz" },
  "austriaeast": { city: "Vienna", countryCode: "at" },
  "belgiumcentral": { city: "Brussels", countryCode: "be" },
  "denmarkeast": { city: "Copenhagen", countryCode: "dk" },
  "indonesiacentral": { city: "Jakarta", countryCode: "id" },
  "malaysiawest": { city: "Kuala Lumpur", countryCode: "my" },
  "chilecentral": { city: "Santiago", countryCode: "cl" },
  "eastus2euap": { city: "Virginia", countryCode: "us" },
  "westus2euap": { city: "Washington", countryCode: "us" },
};

const ORACLE_REGION_INFO: Record<string, RegionInfo> = {
  "us-ashburn-1": { city: "Ashburn", countryCode: "us" },
  "us-phoenix-1": { city: "Phoenix", countryCode: "us" },
  "us-chicago-1": { city: "Chicago", countryCode: "us" },
  "us-sanjose-1": { city: "San Jose", countryCode: "us" },
  "us-saltlake-2": { city: "Salt Lake City", countryCode: "us" },
  "ca-toronto-1": { city: "Toronto", countryCode: "ca" },
  "ca-montreal-1": { city: "Montréal", countryCode: "ca" },
  "sa-saopaulo-1": { city: "São Paulo", countryCode: "br" },
  "sa-vinhedo-1": { city: "Vinhedo", countryCode: "br" },
  "sa-santiago-1": { city: "Santiago", countryCode: "cl" },
  "sa-bogota-1": { city: "Bogotá", countryCode: "co" },
  "eu-frankfurt-1": { city: "Frankfurt", countryCode: "de" },
  "eu-amsterdam-1": { city: "Amsterdam", countryCode: "nl" },
  "eu-zurich-1": { city: "Zurich", countryCode: "ch" },
  "eu-stockholm-1": { city: "Stockholm", countryCode: "se" },
  "eu-marseille-1": { city: "Marseille", countryCode: "fr" },
  "eu-paris-1": { city: "Paris", countryCode: "fr" },
  "eu-madrid-1": { city: "Madrid", countryCode: "es" },
  "eu-milan-1": { city: "Milan", countryCode: "it" },
  "eu-jovanovac-1": { city: "Jovanovac", countryCode: "rs" },
  "uk-london-1": { city: "London", countryCode: "gb" },
  "uk-cardiff-1": { city: "Cardiff", countryCode: "gb" },
  "ap-tokyo-1": { city: "Tokyo", countryCode: "jp" },
  "ap-osaka-1": { city: "Osaka", countryCode: "jp" },
  "ap-seoul-1": { city: "Seoul", countryCode: "kr" },
  "ap-chuncheon-1": { city: "Chuncheon", countryCode: "kr" },
  "ap-mumbai-1": { city: "Mumbai", countryCode: "in" },
  "ap-hyderabad-1": { city: "Hyderabad", countryCode: "in" },
  "ap-singapore-1": { city: "Singapore", countryCode: "sg" },
  "ap-singapore-2": { city: "Singapore", countryCode: "sg" },
  "ap-sydney-1": { city: "Sydney", countryCode: "au" },
  "ap-melbourne-1": { city: "Melbourne", countryCode: "au" },
  "ap-jakarta-1": { city: "Jakarta", countryCode: "id" },
  "ap-malaysia-1": { city: "Kuala Lumpur", countryCode: "my" },
  "ap-malaysia-2": { city: "Johor Bahru", countryCode: "my" },
  "me-jeddah-1": { city: "Jeddah", countryCode: "sa" },
  "me-dubai-1": { city: "Dubai", countryCode: "ae" },
  "me-abudhabi-1": { city: "Abu Dhabi", countryCode: "ae" },
  "af-johannesburg-1": { city: "Johannesburg", countryCode: "za" },
  "af-casablanca-1": { city: "Casablanca", countryCode: "ma" },
  "il-jerusalem-1": { city: "Jerusalem", countryCode: "il" },
  "mx-queretaro-1": { city: "Querétaro", countryCode: "mx" },
  "mx-monterrey-1": { city: "Monterrey", countryCode: "mx" },
  "ap-batam-1": { city: "Batam", countryCode: "id" },
  "ap-kulai-2": { city: "Kulai", countryCode: "my" },
  "eu-madrid-3": { city: "Madrid", countryCode: "es" },
  "eu-turin-1": { city: "Turin", countryCode: "it" },
  "me-riyadh-1": { city: "Riyadh", countryCode: "sa" },
  "sa-valparaiso-1": { city: "Valparaíso", countryCode: "cl" },
};

const REGION_INFO_BY_PROVIDER: Record<string, Record<string, RegionInfo>> = {
  aws: AWS_REGION_INFO,
  gcp: GCP_REGION_INFO,
  azure: AZURE_REGION_INFO,
  oracle: ORACLE_REGION_INFO,
};

export function getRegionInfo(provider: string, regionName: string): RegionInfo {
  const providerMap = REGION_INFO_BY_PROVIDER[provider] ?? {};
  return providerMap[regionName] ?? { city: regionName, countryCode: "" };
}
