interface RegionInfo {
  city: string;
  flag: string;
}

const AWS_REGION_INFO: Record<string, RegionInfo> = {
  "us-east-1": { city: "N. Virginia", flag: "🇺🇸" },
  "us-east-2": { city: "Ohio", flag: "🇺🇸" },
  "us-west-1": { city: "N. California", flag: "🇺🇸" },
  "us-west-2": { city: "Oregon", flag: "🇺🇸" },
  "ca-central-1": { city: "Montréal", flag: "🇨🇦" },
  "ca-west-1": { city: "Calgary", flag: "🇨🇦" },
  "eu-west-1": { city: "Ireland", flag: "🇮🇪" },
  "eu-west-2": { city: "London", flag: "🇬🇧" },
  "eu-west-3": { city: "Paris", flag: "🇫🇷" },
  "eu-central-1": { city: "Frankfurt", flag: "🇩🇪" },
  "eu-central-2": { city: "Zurich", flag: "🇨🇭" },
  "eu-north-1": { city: "Stockholm", flag: "🇸🇪" },
  "eu-south-1": { city: "Milan", flag: "🇮🇹" },
  "eu-south-2": { city: "Spain", flag: "🇪🇸" },
  "ap-east-1": { city: "Hong Kong", flag: "🇭🇰" },
  "ap-northeast-1": { city: "Tokyo", flag: "🇯🇵" },
  "ap-northeast-2": { city: "Seoul", flag: "🇰🇷" },
  "ap-northeast-3": { city: "Osaka", flag: "🇯🇵" },
  "ap-southeast-1": { city: "Singapore", flag: "🇸🇬" },
  "ap-southeast-2": { city: "Sydney", flag: "🇦🇺" },
  "ap-southeast-3": { city: "Jakarta", flag: "🇮🇩" },
  "ap-southeast-4": { city: "Melbourne", flag: "🇦🇺" },
  "ap-southeast-5": { city: "Kuala Lumpur", flag: "🇲🇾" },
  "ap-southeast-7": { city: "Bangkok", flag: "🇹🇭" },
  "ap-south-1": { city: "Mumbai", flag: "🇮🇳" },
  "ap-south-2": { city: "Hyderabad", flag: "🇮🇳" },
  "sa-east-1": { city: "São Paulo", flag: "🇧🇷" },
  "me-south-1": { city: "Bahrain", flag: "🇧🇭" },
  "me-central-1": { city: "UAE", flag: "🇦🇪" },
  "af-south-1": { city: "Cape Town", flag: "🇿🇦" },
  "il-central-1": { city: "Tel Aviv", flag: "🇮🇱" },
  "mx-central-1": { city: "Mexico City", flag: "🇲🇽" },
};

const GCP_REGION_INFO: Record<string, RegionInfo> = {
  "us-central1": { city: "Iowa", flag: "🇺🇸" },
  "us-east1": { city: "S. Carolina", flag: "🇺🇸" },
  "us-east4": { city: "N. Virginia", flag: "🇺🇸" },
  "us-east5": { city: "Columbus", flag: "🇺🇸" },
  "us-south1": { city: "Dallas", flag: "🇺🇸" },
  "us-west1": { city: "Oregon", flag: "🇺🇸" },
  "us-west2": { city: "Los Angeles", flag: "🇺🇸" },
  "us-west3": { city: "Salt Lake City", flag: "🇺🇸" },
  "us-west4": { city: "Las Vegas", flag: "🇺🇸" },
  "northamerica-northeast1": { city: "Montréal", flag: "🇨🇦" },
  "northamerica-northeast2": { city: "Toronto", flag: "🇨🇦" },
  "northamerica-south1": { city: "Querétaro", flag: "🇲🇽" },
  "southamerica-east1": { city: "São Paulo", flag: "🇧🇷" },
  "southamerica-west1": { city: "Santiago", flag: "🇨🇱" },
  "europe-west1": { city: "Belgium", flag: "🇧🇪" },
  "europe-west2": { city: "London", flag: "🇬🇧" },
  "europe-west3": { city: "Frankfurt", flag: "🇩🇪" },
  "europe-west4": { city: "Netherlands", flag: "🇳🇱" },
  "europe-west6": { city: "Zurich", flag: "🇨🇭" },
  "europe-west8": { city: "Milan", flag: "🇮🇹" },
  "europe-west9": { city: "Paris", flag: "🇫🇷" },
  "europe-west10": { city: "Berlin", flag: "🇩🇪" },
  "europe-west12": { city: "Turin", flag: "🇮🇹" },
  "europe-north1": { city: "Finland", flag: "🇫🇮" },
  "europe-central2": { city: "Warsaw", flag: "🇵🇱" },
  "europe-southwest1": { city: "Madrid", flag: "🇪🇸" },
  "asia-east1": { city: "Taiwan", flag: "🇹🇼" },
  "asia-east2": { city: "Hong Kong", flag: "🇭🇰" },
  "asia-northeast1": { city: "Tokyo", flag: "🇯🇵" },
  "asia-northeast2": { city: "Osaka", flag: "🇯🇵" },
  "asia-northeast3": { city: "Seoul", flag: "🇰🇷" },
  "asia-south1": { city: "Mumbai", flag: "🇮🇳" },
  "asia-south2": { city: "Delhi", flag: "🇮🇳" },
  "asia-southeast1": { city: "Singapore", flag: "🇸🇬" },
  "asia-southeast2": { city: "Jakarta", flag: "🇮🇩" },
  "australia-southeast1": { city: "Sydney", flag: "🇦🇺" },
  "australia-southeast2": { city: "Melbourne", flag: "🇦🇺" },
  "me-west1": { city: "Tel Aviv", flag: "🇮🇱" },
  "me-central1": { city: "Doha", flag: "🇶🇦" },
  "me-central2": { city: "Dammam", flag: "🇸🇦" },
  "africa-south1": { city: "Johannesburg", flag: "🇿🇦" },
};

const AZURE_REGION_INFO: Record<string, RegionInfo> = {
  "eastus": { city: "Virginia", flag: "🇺🇸" },
  "eastus2": { city: "Virginia", flag: "🇺🇸" },
  "westus": { city: "California", flag: "🇺🇸" },
  "westus2": { city: "Washington", flag: "🇺🇸" },
  "westus3": { city: "Arizona", flag: "🇺🇸" },
  "centralus": { city: "Iowa", flag: "🇺🇸" },
  "northcentralus": { city: "Illinois", flag: "🇺🇸" },
  "southcentralus": { city: "Texas", flag: "🇺🇸" },
  "westcentralus": { city: "Wyoming", flag: "🇺🇸" },
  "canadacentral": { city: "Toronto", flag: "🇨🇦" },
  "canadaeast": { city: "Québec", flag: "🇨🇦" },
  "brazilsouth": { city: "São Paulo", flag: "🇧🇷" },
  "brazilsoutheast": { city: "Rio de Janeiro", flag: "🇧🇷" },
  "northeurope": { city: "Ireland", flag: "🇮🇪" },
  "westeurope": { city: "Netherlands", flag: "🇳🇱" },
  "uksouth": { city: "London", flag: "🇬🇧" },
  "ukwest": { city: "Cardiff", flag: "🇬🇧" },
  "francecentral": { city: "Paris", flag: "🇫🇷" },
  "francesouth": { city: "Marseille", flag: "🇫🇷" },
  "germanywestcentral": { city: "Frankfurt", flag: "🇩🇪" },
  "germanynorth": { city: "Berlin", flag: "🇩🇪" },
  "switzerlandnorth": { city: "Zurich", flag: "🇨🇭" },
  "switzerlandwest": { city: "Geneva", flag: "🇨🇭" },
  "norwayeast": { city: "Oslo", flag: "🇳🇴" },
  "norwaywest": { city: "Norway", flag: "🇳🇴" },
  "swedencentral": { city: "Gävle", flag: "🇸🇪" },
  "polandcentral": { city: "Warsaw", flag: "🇵🇱" },
  "italynorth": { city: "Milan", flag: "🇮🇹" },
  "spaincentral": { city: "Madrid", flag: "🇪🇸" },
  "eastasia": { city: "Hong Kong", flag: "🇭🇰" },
  "southeastasia": { city: "Singapore", flag: "🇸🇬" },
  "japaneast": { city: "Tokyo", flag: "🇯🇵" },
  "japanwest": { city: "Osaka", flag: "🇯🇵" },
  "koreacentral": { city: "Seoul", flag: "🇰🇷" },
  "koreasouth": { city: "Busan", flag: "🇰🇷" },
  "australiaeast": { city: "Sydney", flag: "🇦🇺" },
  "australiasoutheast": { city: "Melbourne", flag: "🇦🇺" },
  "australiacentral": { city: "Canberra", flag: "🇦🇺" },
  "australiacentral2": { city: "Canberra", flag: "🇦🇺" },
  "centralindia": { city: "Pune", flag: "🇮🇳" },
  "southindia": { city: "Chennai", flag: "🇮🇳" },
  "westindia": { city: "Mumbai", flag: "🇮🇳" },
  "jioindiawest": { city: "Jamnagar", flag: "🇮🇳" },
  "jioindiacentral": { city: "Nagpur", flag: "🇮🇳" },
  "uaenorth": { city: "Dubai", flag: "🇦🇪" },
  "uaecentral": { city: "Abu Dhabi", flag: "🇦🇪" },
  "southafricanorth": { city: "Johannesburg", flag: "🇿🇦" },
  "southafricawest": { city: "Cape Town", flag: "🇿🇦" },
  "israelcentral": { city: "Tel Aviv", flag: "🇮🇱" },
  "qatarcentral": { city: "Doha", flag: "🇶🇦" },
  "mexicocentral": { city: "Querétaro", flag: "🇲🇽" },
  "newzealandnorth": { city: "Auckland", flag: "🇳🇿" },
};

const ORACLE_REGION_INFO: Record<string, RegionInfo> = {
  "us-ashburn-1": { city: "Ashburn", flag: "🇺🇸" },
  "us-phoenix-1": { city: "Phoenix", flag: "🇺🇸" },
  "us-chicago-1": { city: "Chicago", flag: "🇺🇸" },
  "us-sanjose-1": { city: "San Jose", flag: "🇺🇸" },
  "us-saltlake-2": { city: "Salt Lake City", flag: "🇺🇸" },
  "ca-toronto-1": { city: "Toronto", flag: "🇨🇦" },
  "ca-montreal-1": { city: "Montréal", flag: "🇨🇦" },
  "sa-saopaulo-1": { city: "São Paulo", flag: "🇧🇷" },
  "sa-vinhedo-1": { city: "Vinhedo", flag: "🇧🇷" },
  "sa-santiago-1": { city: "Santiago", flag: "🇨🇱" },
  "sa-bogota-1": { city: "Bogotá", flag: "🇨🇴" },
  "eu-frankfurt-1": { city: "Frankfurt", flag: "🇩🇪" },
  "eu-amsterdam-1": { city: "Amsterdam", flag: "🇳🇱" },
  "eu-zurich-1": { city: "Zurich", flag: "🇨🇭" },
  "eu-stockholm-1": { city: "Stockholm", flag: "🇸🇪" },
  "eu-marseille-1": { city: "Marseille", flag: "🇫🇷" },
  "eu-paris-1": { city: "Paris", flag: "🇫🇷" },
  "eu-madrid-1": { city: "Madrid", flag: "🇪🇸" },
  "eu-milan-1": { city: "Milan", flag: "🇮🇹" },
  "eu-jovanovac-1": { city: "Jovanovac", flag: "🇷🇸" },
  "uk-london-1": { city: "London", flag: "🇬🇧" },
  "uk-cardiff-1": { city: "Cardiff", flag: "🇬🇧" },
  "ap-tokyo-1": { city: "Tokyo", flag: "🇯🇵" },
  "ap-osaka-1": { city: "Osaka", flag: "🇯🇵" },
  "ap-seoul-1": { city: "Seoul", flag: "🇰🇷" },
  "ap-chuncheon-1": { city: "Chuncheon", flag: "🇰🇷" },
  "ap-mumbai-1": { city: "Mumbai", flag: "🇮🇳" },
  "ap-hyderabad-1": { city: "Hyderabad", flag: "🇮🇳" },
  "ap-singapore-1": { city: "Singapore", flag: "🇸🇬" },
  "ap-singapore-2": { city: "Singapore", flag: "🇸🇬" },
  "ap-sydney-1": { city: "Sydney", flag: "🇦🇺" },
  "ap-melbourne-1": { city: "Melbourne", flag: "🇦🇺" },
  "ap-jakarta-1": { city: "Jakarta", flag: "🇮🇩" },
  "ap-malaysia-1": { city: "Kuala Lumpur", flag: "🇲🇾" },
  "ap-malaysia-2": { city: "Johor Bahru", flag: "🇲🇾" },
  "me-jeddah-1": { city: "Jeddah", flag: "🇸🇦" },
  "me-dubai-1": { city: "Dubai", flag: "🇦🇪" },
  "me-abudhabi-1": { city: "Abu Dhabi", flag: "🇦🇪" },
  "af-johannesburg-1": { city: "Johannesburg", flag: "🇿🇦" },
  "af-casablanca-1": { city: "Casablanca", flag: "🇲🇦" },
  "il-jerusalem-1": { city: "Jerusalem", flag: "🇮🇱" },
  "mx-queretaro-1": { city: "Querétaro", flag: "🇲🇽" },
  "mx-monterrey-1": { city: "Monterrey", flag: "🇲🇽" },
};

const REGION_INFO_BY_PROVIDER: Record<string, Record<string, RegionInfo>> = {
  aws: AWS_REGION_INFO,
  gcp: GCP_REGION_INFO,
  azure: AZURE_REGION_INFO,
  oracle: ORACLE_REGION_INFO,
};

export function getRegionInfo(provider: string, regionName: string): RegionInfo {
  const providerMap = REGION_INFO_BY_PROVIDER[provider] ?? {};
  return providerMap[regionName] ?? { city: regionName, flag: "🌍" };
}
