[package]
name = "ui"
version.workspace = true
description = "A Tauri App"
authors = ["you"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { workspace = true, features = ["tray-icon", "specta"] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"
tauri-plugin-store = "2"
chrono = { workspace = true }
humantime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
specta-typescript = "=0.0.12"
tauri-specta = { version = "=2.0.0-rc.25", features = ["derive", "typescript"] }
byocvpn_core = { path = "../../core", features = ["specta"] }
byocvpn_aws = { path = "../../infra/aws", features = ["specta"] }
byocvpn_oracle = { path = "../../infra/oracle", features = ["specta"] }
byocvpn_gcp = { path = "../../infra/gcp", features = ["specta"] }
byocvpn_azure = { path = "../../infra/azure", features = ["specta"] }
tokio = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
byocvpn_daemon = { path = "../../daemon" }

[target.'cfg(target_os = "android")'.dependencies]
tauri-plugin-android-vpn = { path = "../../android" }
android_logger = "0.15"
async-trait = { workspace = true }
tun-rs = { workspace = true }
