[package]
name = "byocvpn_core"
version.workspace = true
edition = "2024"

[dependencies]

thiserror = { workspace = true }
log = { workspace = true }
base64 = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rust-ini = "0.21.3"
ipnet = { workspace = true, features = ["serde"] }

boringtun = "0.7.1"
tun-rs = { workspace = true }
dirs = "7.0.0"
rand = { workspace = true }
handlebars = { workspace = true }
chrono = { workspace = true }
strum = { workspace = true }
specta = { workspace = true, optional = true }

[features]
specta = ["dep:specta"]

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
] }
